"""Stats for the matbench_perovskites dataset.

Input: Pymatgen Structure of the material.
Target variable: Heat of formation of the entire 5-atom perovskite cell in eV
    as calculated by RPBE GGA-DFT. Note the reference state for oxygen was
    computed from oxygen's chemical potential in water vapor, not as oxygen
    molecules, to reflect the application which these perovskites were studied for.
Entries: 18,928

Matbench v0.1 dataset for predicting formation energy from crystal structure.
Adapted from an original dataset generated by Castelli et al.

https://ml.materialsproject.org/projects/matbench_perovskites
"""


# %%
import matplotlib.pyplot as plt
from matminer.datasets import load_dataset
from pymatgen.ext.matproj import MPRester
from pymatviz import (
    annotate_bar_heights,
    ptable_heatmap,
    spacegroup_hist,
    spacegroup_sunburst,
)
from tqdm import tqdm


# %%
df_perov = load_dataset("matbench_perovskites")

df_perov[["sg_symbol", "sg_number"]] = [
    struct.get_space_group_info() for struct in tqdm(df_perov.structure)
]


# %%
df_perov.hist(column="e_form", bins=50)
plt.savefig("perovskites-e_form-hist.pdf")


# %%
df_perov["formula"] = df_perov.structure.apply(lambda cryst: cryst.formula)

ptable_heatmap(df_perov.formula, log=True)
plt.title("Elemental prevalence in the Matbench perovskites dataset")
plt.savefig("perovskites-ptable-heatmap-log.pdf")


# %%
df_perov["volume"] = df_perov.structure.apply(lambda struct: struct.volume)

df_perov.hist(column="volume", bins=50, log=True)


# %%
mpr = MPRester()
df_perov["likely_mp_ids"] = [mpr.find_structure(x) for x in tqdm(df_perov.structure)]


# %%
mp_ids = df_perov.likely_mp_ids.explode().value_counts().index.to_list()

es_above_hull = mpr.query({"material_id": {"$in": mp_ids}}, ["e_above_hull"])


# %%
ax = df_perov.likely_mp_ids.apply(len).value_counts().plot(kind="bar", log=True)
annotate_bar_heights()
plt.savefig("likely_mp_ids_lens.pdf")


# %%
spacegroup_hist(df_perov.sg_number)
plt.savefig("perovskites-spacegroup-hist.pdf")


# %%
df_perov["crystal_system"].value_counts().plot.bar()

plt.title("Crystal systems in Matbench Perovskites")
plt.xticks(rotation="horizontal")

annotate_bar_heights(voffset=250)

plt.savefig("perovskites-crystal-system-counts.pdf")


# %%
df_perov.plot.scatter(x="volume", y="e_form", c="sg_number", colormap="viridis")


# %%
fig = spacegroup_sunburst(df_perov.sg_number, show_values="percent")
fig.update_layout(title="Spacegroup sunburst of the JARVIS DFT 2D dataset")
fig.write_image("jdft2d-spacegroup-sunburst.pdf")
fig.show()
